"""empty message

Revision ID: 9e30eb4fd79a
Revises: 
Create Date: 2021-05-29 21:15:48.875820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e30eb4fd79a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_index(op.f('ix_members_first_name'), 'members', ['first_name'], unique=False)
    op.create_index(op.f('ix_members_last_name'), 'members', ['last_name'], unique=False)
    op.create_index(op.f('ix_members_username'), 'members', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_members_username'), table_name='members')
    op.drop_index(op.f('ix_members_last_name'), table_name='members')
    op.drop_index(op.f('ix_members_first_name'), table_name='members')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###
